### ISSUE TITLE
Error with properties with same name

### ISSUE THREAD

**Issue by iremmats** [urielha/log4stash-old#2]
Ran into this error when trying to use the appender. Background is that we are using our own built logging framework built upon Log4Net. What we have there is basically some extra properties.

System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at log4net.ElasticSearch.ElasticSearchAppender.CreateLogEvent(LoggingEvent loggingEvent) in d:\uriel\Programing\C#\log4stash\src\log4net.ElasticSearch\ElasticSearchAppender.cs:line 235
   at log4net.ElasticSearch.ElasticSearchAppender.Append(LoggingEvent loggingEvent) in d:\uriel\Programing\C#\log4stash\src\log4net.ElasticSearch\ElasticSearchAppender.cs:line 112
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)

**Comment by urielha** [comment]
Hi @iremmats,
Do want the value of the properties to be appended into list?
Say you have "Prop1"="val1" and "Prop1"="val2"
you want it to be serialized as "Prop1" => ["val1", "val2"] ?

**Comment by urielha** [comment]
Anyway, 
Try this version @42c0f9dbeec0b9a97726ee9e307d4c23823fec46

Or install it via nuget:

```
Install-Package log4stash -Version 1.0.1-Pre -Pre 
```

Tell me if it works =]

**Comment by iremmats** [comment]
Hi,

Will try later today. Let me know if you want some help with this project. My company is using log4net + ES alot.

/Mats Iremark

26 dec 2014 kl. 13:59 skrev Uriel Hai <notifications@github.com<mailto:notifications@github.com>>:

Anyway,
Try this version @42c0f9dhttps://github.com/urielha/log4stash/commit/42c0f9dbeec0b9a97726ee9e307d4c23823fec46

Or install it via nuget:

Install-Package log4stash -Version 1.0.1-Pre -Pre

Tell me if its work =]

##

**Comment by iremmats** [comment]
Hi,

It works with that version. Don't know what you changed under the hood but let me just explain what I modified in the source code to also get it working.

if (logEvent.ContainsKey(propertyKey))
                    {
                        logEvent[propertyKey] = properties[propertyKey].ToString();
                    }
                    else
                    {
                           logEvent.Add(propertyKey, properties[propertyKey].ToString());
                    }

Basically in the ElasticSearchAppender.cs there was this logEvent.Add that crashed because there was already a property with that name. Just made a check if it already existed before overwriting it.

One more question, in this method:

private Dictionary<string, object> CreateLogEvent(LoggingEvent loggingEvent)

Why do you have lines like these?
logEvent["@timestamp"] = loggingEvent.TimeStamp.ToUniversalTime().ToString("O");
            logEvent["LoggerName"] = loggingEvent.LoggerName;
            logEvent["ThreadName"] = loggingEvent.ThreadName;
....

I don't know about every single property set as standard in log4net but doesn't these already come out of the box?

The way we are using log4net is that we have our own logging framework that has its own properties. That means we basically Clear all standard variables from log4net Context and use our own instead. When the appender then adds some extra props we have to use the Remove-filter in the configuration.

Hope you understood all my technical yada yada and thanks for the help fixing it. Always better to have it working out of the box than changing the source code ourselves.

/Mats

**Comment by urielha** [comment]
Hi,
I'm glad to hear it works!
I decided to append the value into a list.
Instead of one value, the property will have two or more....
Is that OK?
But I need to know, can you tell me how come you have two properties with the same key name?

About the second question,
the properties of log4net are 'lazy' so if you don't actually read them they won't be generated 
so I need to read them one by one. I hope I will find another approach to do this.

But, instead of remove them you can use the FixedFields configuration parameter.
Try to add this into the ElasticSearchAppender configuration xml:

``` xml
    <FixedFields>Properties, Message</FixedFields>
```

**Comment by iremmats** [comment]
Hi,

For our purpose and most I think its better to override than to append in a list. The lower contexts should override the higher ones.

Good point about the lazy properties. That work is being done in the appenders of course.

Ill try the fixed field parameter, that would be perfect in our case. Thanks alot! :)

/Mats Iremark

28 dec 2014 kl. 01:03 skrev Uriel Hai <notifications@github.com<mailto:notifications@github.com>>:

Hi,
I'm glad to hear it works!
I decided to append the value into a list.
Instead of one value, the property will have two or more....
Is that OK?
Soon I will release stable version with this feature.

About the second question,
the properties of log4net are 'lazy' so if you don't actually read them they won't be generated
so I need to read them one by one. I hope I will find another approach to do this.

But, instead of remove them you can use the FixedFields configuration parameter.
Try this:

```
<FixedFields>Properties, Message</FixedFields>
```

##

**Comment by urielha** [comment]
Fixed :)
Please update to the latest version (1.0.1)
