### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ITFactoryAUT** [urielha/log4stash-old#3]
Hello,
is there any documentation available?
I want to use logstash for centralizing the logs of all my application, but I have no idea how to connect the server through log4stash to my programs.
greetings

**Comment by urielha** [comment]
Hi,
I didn't managed to write good documentation yet, but there is a lot of documentations about log4net, logstash and elasticsearch out there.

Are you using log4net to write your logs?
Do you already have Elasticsearch server?

With log4stash you can skip logstash and write your logs right to your Elasticsearch server without loosing the 'power' of logstash filters..

**Comment by Cylindric** [comment]
So before I dive in start using this, I assume I should consider it more of a "log4elastic" than a "log4stash", as at no point does logstash come into it?

**Comment by urielha** [comment]
yes, the meaning is that this appender can replace your "logstash chain" (because it has few of its useful features).
 the name is just cool ;)

**Comment by Cylindric** [comment]
Hah, that it is. And, I've just got it into my app with about 5 minutes of effort, so thanks!

**Comment by MonDeveloper** [comment]
I'm looking for documentation too.
especially about the configuration part where even a quick & dirty guide for all the possibile parameters could be a great help for any guys like me and it shouldn't be a huge effort for you. (I hope)

**Comment by urielha** [comment]
Yes I'm planing to publish such kind of documentation but lately I don't have much time to spare for this.
For now you have two versions of documentations on the readme - one is the basic and the other more detailed.
Hope to update soon.

**Comment by urielha** [comment]
This issue was moved to urielha/log4stash#1
