### ISSUE TITLE
ElasticSearchAppender does not handle property with null value

### ISSUE THREAD

**Issue by RedwoodForest** [urielha/log4stash-old#7]
If I set the appender to submit the properties fields to elastic search and one of the properties has a null value then the appender fails to submit any data. In my case the builtin log4net property "log4net:UserName" had a null value, so it's not as simple as making sure I don't configure any properties with a null value since the value is coming from log4net.

It looks like this may be the issue:

```
if (FixedFields.ContainsFlag(FixFlags.Properties))
{
    var properties = loggingEvent.GetProperties();
    foreach (var propertyKey in properties.GetKeys())
    {
        logEvent[propertyKey] = properties[propertyKey].ToString();
    }
}
```

Specifically the call to `properties[propertyKey].ToString()` without checking that the value is not null first.

Thanks for all your work on this, it's a very useful library.

**Comment by urielha** [comment]
Hi @lawrencejohnston,
Thanks for the contributions!
I will add a fix and a test for that soon

Uriel

**Comment by urielha** [comment]
Try to install this pre-release version and tell if this work:

> Install-Package log4stash -Version 1.0.2-Pre2 -Pre

**Comment by RedwoodForest** [comment]
Yup, that fixes the issue.

**Comment by urielha** [comment]
Once a stable version with the fix will released I will close this issue.
Thanks!
