### ISSUE TITLE
Performance Improvements to ElasticClient

### ISSUE THREAD

**Issue by yosiat** [urielha/log4stash-old#9]
Hi,

I have read the code of ElasticClient, and I have some tips to improve performance of indexing:
- You are using .NET JavascriptSerializer, which is horribly slow and you are recreating it's instance every serialize (which clears it's internal cache), I recommend using [Jil](https://github.com/kevin-montrose/Jil)
- Instead of using WebRequest (and it's ugly Begin/End async pattern), you can use HttpClient and execute PutAsync/PostAsync - from my tests, It handles concurrency pretty well.

I will submit a pull request on the weekend If I will have time.

**Comment by RichiCoder1** [comment]
We're just looking into this now. Agree with yosiat's points and will happily pick this up if needed :).

**Comment by urielha** [comment]
Thaks @yosiat :)
Sounds very good.
I will try your offer ASAP.
But let me know if you currently working on pull request - I will be happy to apply it.

**Comment by yosiat** [comment]
I currently don't have time to work on the pull request, maybe during the
next week.

**Comment by rostiar** [comment]
+1

**Comment by urielha** [comment]
Unfortunately Jil is not supporting .NET4.0 and .NET3.5
I will check for another solution, or maybe till then Jil will be released also on those frameworks.

**Comment by yosiat** [comment]
@urielha instead of Jil, you can checkout Newtonsoft.Json/ServiceStack.Json it will be much faster than JavascriptSerializer that comes with .net

**Comment by urielha** [comment]
This issue was moved to urielha/log4stash#2
